window.bndlkt = {
	bundlesIndexMap: new Map(),
	bundlesIdMap: new Map(),

	modules: {}, // { "react@19.2.6": factoryFn, 0: factoryFn }

	injectScript(url) {
		return new Promise((resolve, reject) => {
			const script = document.createElement('script');
			script.src = url;
			script.async = true;
			script.onload = () => {
				console.log(`🟢 [bndlkt] Script executed successfully: ${url}`);
				resolve();
			};
			script.onerror = () => {
				console.error(`🔴 [bndlkt] Script load failed: ${url}`);
				reject(new Error(`[bndlkt] Load error: ${url}`));
			};
			document.head.appendChild(script);
		});
	},

	getCookie(name) {
		const value = `; ${document.cookie}`;
		const parts = value.split(`; ${name}=`);
		if (parts.length === 2) {
			return parts.pop().split(';').shift();
		}
		return null;
	},

	bootstrap(configUrl) {
		const scope = this.getCookie('bndlkt-scope') || 'release';
		const url = `${configUrl}?scope=${encodeURIComponent(scope)}&rid=${Date.now()}`;
		return fetch(url)
			.then((res) => {
				if (!res.ok) {
					throw new Error(`HTTP ${res.status}`);
				}
				return res.json();
			})
			.then((config) => this.init(config))
			.catch((err) => {
				console.error('Failed to load config, using fallback', err);
				// could use a default config, but not yet
			});
	},

	init({ bundles, env }) {
		console.log('⚙️ [bndlkt] Updating package graph configuration...');
		this.bundlesIndexMap.clear();
		this.bundlesIdMap.clear();
		this.env = env;

		Object.keys(bundles).forEach((bundleIndex) => {
			const bundle = bundles[bundleIndex];
			const index = parseInt(bundleIndex, 10);

			this.bundlesIndexMap.set(index, bundle);
			this.bundlesIdMap.set(bundle.id, {
				index,
				...bundle,
			});
		});
		console.log(
			`✅ [bndlkt] Graph successfully loaded. Registered packages: ${this.bundlesIndexMap.size}`,
		);

		this.require(0);
	},

	register(bndlktId, factoryFn) {
		console.log(`📦 [bndlkt] Bundle received for registration: "${bndlktId}"`);
		if (!this.modules[bndlktId]) {
			this.modules[bndlktId] = {
				initialized: false,
				exports: null,
				factory: factoryFn,
			};
		}
		this.modules[bndlktId].factory = factoryFn; // todo ???
	},

	async require(bundleIndex) {
		console.log(
			`🚀 [bndlkt] Request to launch package with index [${bundleIndex}] (${this.bundlesIndexMap.get(bundleIndex).id})...`,
		);

		await this.fetchDependencyBundles(bundleIndex);

		return this.initializeModule(bundleIndex);
	},

	loadingPromises: {},
	async fetchDependencyBundles(bundleIndex, loaded = new Set()) {
		if (loaded.has(bundleIndex)) {
			return;
		}

		loaded.add(bundleIndex);

		const bundle = this.bundlesIndexMap.get(bundleIndex);

		if (!bundle) {
			throw new Error(`[bndlkt] Package with index ${bundleIndex} is missing from the config!`);
		}

		if (this.loadingPromises[bundleIndex]) {
			return this.loadingPromises[bundleIndex];
		}

		const { id: bundleId, baseUrl, files, deps = [] } = bundle;

		this.loadingPromises[bundleIndex] = (async () => {
			// Start dependency promises IMMEDIATELY, without awaiting them
			const dependencyPromises = deps.map((depIndex) => this.fetchDependencyBundles(depIndex));

			// Simultaneously start network loading of the CURRENT package files
			const currentFilePromise = (() => {
				if (!this.modules[bundleIndex]?.factory) {
					console.log(
						`🌐 [bndlkt] Network request (PARALLEL): downloading scripts for [${bundleIndex}] (${bundleId})...`,
					);
					return Promise.all(
						files.map((file) => {
							const baseUrlFixed = baseUrl.endsWith('/') ? baseUrl : baseUrl + '/';
							// todo currently only scripts
							return this.injectScript(`${baseUrlFixed}${file}`);
						}),
					);
				}

				return Promise.resolve();
			})();

			// Wait for SIMULTANEOUS completion of both the current package files and all its dependency files
			await Promise.all([
				...dependencyPromises,
				currentFilePromise,
			]);
		})();

		return this.loadingPromises[bundleIndex];
	},

	resolveDependencyIndex(requesterIndex, depName) {
		const bundle = this.bundlesIndexMap.get(requesterIndex);

		const { deps, lazyDeps } = bundle;
		const allowedDeps = [
			...deps,
			...lazyDeps,
		];

		for (const depIndex of allowedDeps) {
			const depPkg = this.bundlesIndexMap.get(depIndex);

			if (!depPkg) {
				continue;
			} // todo warning

			const lastAtIndex = depPkg.id.lastIndexOf('@');
			const cleanDepName = lastAtIndex !== -1 ? depPkg.id.substring(0, lastAtIndex) : depPkg.id;

			if (cleanDepName === depName) {
				return depIndex;
			}
		}

		throw new Error(
			`[bndlkt] Usage of "${depName}" is forbidden by the graph for package ${requesterIndex}.`,
		);
	},
	/**
	 * Module initialization. Returns the CLEAN module.exports generated by Webpack.
	 */
	initializeModule(bundleIndex) {
		const { id: bundleId } = this.bundlesIndexMap.get(bundleIndex);

		if (this.modules[bundleId].initialized) {
			return this.modules[bundleId].exports;
		}

		const factory = this.modules[bundleId].factory;

		if (!factory) {
			throw new Error(`[bndlkt] Factory for package ${bundleIndex} not found.`);
		}

		// Create an isolated CommonJS context
		const customModule = {
			exports: {},
		};

		// Set initialized = true BEFORE running the factory to correctly resolve circular dependencies.
		// todo: if the factory throws, this flag remains true and the module stays in a broken state – it should be reset.
		this.modules[bundleId].initialized = true;

		const localRequire = (depName) => {
			const targetIndex = this.resolveDependencyIndex(bundleIndex, depName);
			return this.initializeModule(targetIndex);
		};

		// Run the factory, firmly binding the context to exports
		factory.call(customModule.exports, localRequire, customModule, customModule.exports);

		// Strictly after factory, as it may overwrite the original reference
		this.modules[bundleId].exports = customModule.exports; // pass the reference

		return customModule.exports;
	},

	async requireLazy(issuerId, depName) {
		console.log(`🦥 [bndlkt] Dynamic import: "${depName}" from package "${issuerId}"`);

		// Get the calling module from the ready map by its string bndlktId
		const issuerBundle = this.bundlesIdMap.get(issuerId);
		if (!issuerBundle) {
			throw new Error(`[bndlkt] Calling package "${issuerId}" not found in the graph!`);
		}

		// We need its index for resolveDependencyIndex.
		// To avoid searching, we take it directly from the bundle object,
		// because during init() you saved the bundleIndex there (update init below if needed)

		const requesterIndex = issuerBundle.index;

		// Find the lazy dependency index by its short name
		const targetIndex = this.resolveDependencyIndex(requesterIndex, depName);

		// Download and launch
		await this.fetchDependencyBundles(targetIndex);
		return this.initializeModule(targetIndex);
	},
};
